# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import event_pb2 as event__pb2


class EventServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribePeriodic = channel.unary_stream(
                '/eventPackage.EventService/SubscribePeriodic',
                request_serializer=event__pb2.PeriodicSubscription.SerializeToString,
                response_deserializer=event__pb2.Event.FromString,
                )
        self.SubscribeOnCondition = channel.unary_stream(
                '/eventPackage.EventService/SubscribeOnCondition',
                request_serializer=event__pb2.OnConditionSubscription.SerializeToString,
                response_deserializer=event__pb2.Event.FromString,
                )
        self.Ping = channel.unary_stream(
                '/eventPackage.EventService/Ping',
                request_serializer=event__pb2.Empty.SerializeToString,
                response_deserializer=event__pb2.Empty.FromString,
                )


class EventServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribePeriodic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeOnCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribePeriodic': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribePeriodic,
                    request_deserializer=event__pb2.PeriodicSubscription.FromString,
                    response_serializer=event__pb2.Event.SerializeToString,
            ),
            'SubscribeOnCondition': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeOnCondition,
                    request_deserializer=event__pb2.OnConditionSubscription.FromString,
                    response_serializer=event__pb2.Event.SerializeToString,
            ),
            'Ping': grpc.unary_stream_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=event__pb2.Empty.FromString,
                    response_serializer=event__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eventPackage.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribePeriodic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/eventPackage.EventService/SubscribePeriodic',
            event__pb2.PeriodicSubscription.SerializeToString,
            event__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeOnCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/eventPackage.EventService/SubscribeOnCondition',
            event__pb2.OnConditionSubscription.SerializeToString,
            event__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/eventPackage.EventService/Ping',
            event__pb2.Empty.SerializeToString,
            event__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
